const posts = [{
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 2,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 3,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 4,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 5,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 6,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 7,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 8,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 9,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 10,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 11,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 12,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 13,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 14,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 15,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 16,
    userName: 'Everything',
    likes: 'Everything'
  }]

  export default posts;
