const posts = [{
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }, {
    profileImg: 'Everything',
    key: 1,
    userName: 'Everything',
    likes: 'Everything'
  }]

  export default posts;
